language: ruby
rvm:
- 2.4.0
before_script:
- bundle exec rake db:create --all
- bundle exec rake db:migrate
script:
- bundle exec rake ci:tests
services:
- postgresql
notifications:
  email: false
deploy:
provider: heroku
api_key:
  secure: "fN24YRxlDz8XxfTrQIpV3g5T/ANBNJx91cGvdDDkYii7KhpyFHqZdHN91xdNzukw0hUj/2EEFjIj2Jm9Nh6JPg3zVqWa+uTOSKDH1zB1P5j2qQ/hT7omIed8VRIRK20ZDtr0zYWeduZaOl/MMkh/phs7fJ9X7AD0QyKWt2A8SXZxESybXvxy8vw6kk9gt6AXdsVYW3oI/AAJAHtNK0LOO4c/Wn4+aw6Z3odEs7OJIkYdLKlla+00aezTU3OOIqzToM6l+mtxGd3wqYfHCjsYCLF+3A95y5Anxtj79X4wMxsVgndv8HbaBjwKE1XuzGQX0LXiRnlynCSEuwzWsy4F4YGLBnyP8EaSl6AIBQNjPOWbTuRi9X8mTo2j6GgsCpSdvGfcGrGGNFrUCrzUwC0MKFr7Ikj5jLVyxcQzQ8b8EtKZn0LD0W9g+aqTpdlV/lw85mIz1SOi/covfjCeANsyuACQhWpgCyHDoplGem5q4YYIvlZpa0DR+/spIMIh77Zql6h4Pcl/NVbmf829vpjJMokjsqzI70MIDyt3lBRTMMnQNI2HldJolTy9kv0YUBReaudAJWoeWI+jg4wEUnDeJaCbgeOIHj2aksTvfkDLNzKakaLTW8H1ALWGtHOWB05SQQMmyMlWF9GNmdHWLyRPzrEUqyNIjcn2MkMdVQaamjU="
